apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
    type: back-end

spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-app
      type: back-end
  template:
    metadata:
      labels:
        app: nginx-app
        type: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # 최대 몇 개씩 삭제를 할지
      maxSurge: 1 # 최대 몇 개씩 생성을 할지
