apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Mi
  # volumeMode: Filesystem
  accessModes:
    # ReadWriteOnce (RWO) - Read Write Mode로 하나의 노드만 점유 가능
    # ReadOnlyMany (ROX) - Read Only로 여러 노드 점유 가능
    # ReadWriteMany (RWX) - Read Write Mode로 여러 노드 점유 가능 (NFS)
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: '/mnt/data' # Docker Host 내 존재하는 폴더
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
