apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    name: nginx-app
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: nginx-secret
