apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip-service
spec:
  selector:
    app: nginx # template metadata
  type: ClusterIP
  ports:
    - port: 80 # Cluster Port
      targetPort: 80 # Container Port

# kubectl run test-curl --rm -it --image=curlimages/curl -- /bin/sh
# curl nginx-cluster-ip-service
