name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-gateway:latest -t jongmany/fc-nest-gateway:${{ github.sha }} -f ./apps/gateway/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-notification:latest -t jongmany/fc-nest-notification:${{ github.sha }} -f ./apps/notification/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-order:latest -t jongmany/fc-nest-order:${{ github.sha }} -f ./apps/order/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-payment:latest -t jongmany/fc-nest-payment:${{ github.sha }} -f ./apps/payment/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-product:latest -t jongmany/fc-nest-product:${{ github.sha }} -f ./apps/product/Dockerfile --target production --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t jongmany/fc-nestjs-user:latest -t jongmany/fc-nest-user:${{ github.sha }} -f ./apps/user/Dockerfile --target production --push .
